name: autofix.ci

on:
  pull_request:
  push:
    branches:
      - "master"
      - "develop"

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Install Packages
        run: pnpm install

      - name: TypeScript Check
        run: pnpm types:check

      - name: Run AutoFix
        uses: autofix-ci/action@dd55f44df8f7cdb7a6bf74c78677eb8acd40cd0a
