name: Deploy
on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install step
        run: "bun install"

      - name: Build step
        run: "bun run build"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "todo-list-vite"
          entrypoint: "https://deno.land/std@0.217.0/http/file_server.ts"
          root: "dist"
          
