name: Sync branch

on:
  push:
    branches:
      - master

jobs:
  sync-branch:
    name: Update next branch
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master
      - uses: connor-baer/action-sync-branch@v1.1.0
        with:
          branch: v1
          token: ${{ secrets.GITHUB_TOKEN }}
          # Force push is enabled since v1 is supposed to be an exact copy of master until breaking changes are made
          force: true
